### ISSUE TITLE
Settings - update user profile

### ISSUE THREAD

**Issue by vilsbole** [vilsbole/realworld-vue#3]
Allow user to update info in /settings/:username

**Comment by igeligel** [comment]
Ill take this one :)

**Comment by disjfa** [comment]
19 days, if you don't like to get this one i kinda had some changes already. Also started with some getters in the state for user and stuff.

**Comment by igeligel** [comment]
Hmm, yeah you can start, sry was kind of busy with other stuff. Will probably come back at some point and improve / add features if it is ok 👍

**Comment by disjfa** [comment]
Help is always awesome.
