### ISSUE TITLE
add default text when feed is empty

### ISSUE THREAD

**Issue by vilsbole** [vilsbole/realworld-vue#31]
Default text = "No articles are here... yet."

Current screen:
<img width="793" alt="screen shot 2017-11-18 at 15 39 08" src="https://user-images.githubusercontent.com/2429708/32981487-cf14abd0-cc76-11e7-9521-18d364b5c5e0.png">

Should be:
<img width="789" alt="screen shot 2017-11-18 at 15 39 49" src="https://user-images.githubusercontent.com/2429708/32981488-cf2cc6e8-cc76-11e7-8fc6-925165f95f20.png">

**Comment by disjfa** [comment]
https://github.com/vilsbole/realworld-vue/pull/39
