### ISSUE TITLE
correct routes for profile page

### ISSUE THREAD

**Issue by vilsbole** [vilsbole/realworld-vue#32]
- [x] default url for profile should be  `/#/@John%20Barter` not `/#/@John%20Barter/articles`
- [x] url for favorited articles should be `/#/@John%20Barter/favorites` not `/#/@John%20Barter/favorited`

**Comment by disjfa** [comment]
The first one is hard, not because we cannot delete the path on the sub route, but router thinks the route is active when on the Favorites tab. So both tabs are active instead of one.

**Comment by vilsbole** [comment]
solved with by:
- providing setting the child as default route and removing the name from the parent. ie. vue-router [issue 777](https://github.com/vuejs/vue-router/issues/777)
- using `exact` directive on `router-link`
