### ISSUE TITLE
Remove # in router

### ISSUE THREAD

**Issue by disjfa** [vilsbole/realworld-vue#47]
Router defaults to #hash routes, i want to change that to history so the routes stay clean.

https://router.vuejs.org/en/api/options.html#mode

**Comment by vilsbole** [comment]
It seems that #hash routing is required in the [specs](https://github.com/gothinkster/realworld/tree/master/spec)

**Comment by disjfa** [comment]
Well, than we leave it. Doesn't matter for the inner workings.
