### ISSUE TITLE
Feed - pagination

### ISSUE THREAD

**Issue by vilsbole** [vilsbole/realworld-vue#5]
Implement pagination logic

**Comment by igeligel** [comment]
I want to help you here. Is it possible that i can do this? Probably assign me here 👍

**Comment by vilsbole** [comment]
@igeligel Sure that would be great!
For the moment we pass a params object to `axios.get` which transforms the filters into a query, but feel free to make suggestions.

**Comment by igeligel** [comment]
Yeah saw your latest commits 👍 Whats your opinion on using the [styleguide](https://vuejs.org/v2/style-guide/index.html) which was released recently throughout the project? Probably create another issue for this.

**Comment by vilsbole** [comment]
Excellent suggestion. I've created a new issue #14 to track progress
